openapi: 3.0.0
info:
  title: OpenAPI Oliver
  description: This is a sample server Oliver server. For this sample, you can use the api key `special-key` to test the authorization filters. For OAuth2 flow, you may use `user` as both username and password when asked to login.
  license:
    name: Apache-2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about OpenAPI generator
  url: https://openapi-generator.tech
tags:
- name: mo
  description: MO
paths:
  /mo:
    post:
      tags:
      - mo
      summary: Add a new mo to the store
      operationId: addPet
      requestBody:
        $ref: '#/components/requestBodies/MO'
      responses:
        405:
          description: Invalid input
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      x-accepts: application/json
      x-tags:
      - tag: mo
      x-contentType: application/json
  
components:
  schemas:
    MO:
      title: Miscellaneous Obligation
      type: object
      properties:
        sourceSystem:
          type: string
          example: DML
        destinationSystem:
          type: string
          example: FMS
        submittingStation:
          type: string
          example: 556
        transactionClass:
          type: string
          example: DOC
        transactionCode:
          type: string
          example: MO
        sec1Code:
          type: string
          example: 10  
        batchNumber:
          type: string
          example: 09C556
        transactionNumber:
          type: string
          example: 5564B0901 
        transactionDate:
          type: string
          example: 20231209
        transactionTime:
          type: string
          example: 070001
        sequenceNumber:
          type: string
          example: 001 
        sequenceTotal:
          type: string
          example: 001 
        version:
          type: string
          example: 001 

 
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        transactionType:
          type: string
          description: HDR Trans Type
          enum:
          - Original
          - Modification
          - Cancelation
        fundCode:
          type: string
          example: 0169N1
        costOrganization:
          type: string
          example: 746300
        costSubOrg:
          type: string
          example: 00
        xprogram:
          type: string
          example: 0700DML02
        budgetObjectCode:
          type: string
          example: 2638
        lineAmount:
          type: string
          example: 102.15
        lineAction:
          type: string
          example: D

        complete:
          type: boolean
          default: false
      description: A miscellaneous order (or obligation) document for reporting funds obligated for general materiel that has been ordered from a source of supply (line items not including fixed assets). Also known as the Miscellaneous Order (MO) Document for either a 2138 (items), 1358 (services), or purchase order (see Section 3 of VistA IFCAP v5.1 Accounting Technician User's Guide, MO code sheet in VA DHCP Generic Code Sheet Technical Manual, file 424 in VistA IFCAP v5.1 Technical Manual, and 1358 and obligation topics in VistA IFCAP v5.1 Security Guide).
      example:
        sourceSystem: DML
        destinationSystem: FMS
        submittingStation: 556
        transactionClass: DOC
        transactionCode: MO
        sec1Code: 10  
        batchNumber: 09C556
        transactionNumber: 5564B0901 
        transactionDate: 20231209
        transactionTime: 070001
        sequenceNumber: 001
        sequenceTotal: 001
        version: 001
        transactionType: Modification
        fundCode: 0169N1
        costOrganization: 746300
        costSubOrg: 00
        xprogram: 0700DML02
        budgetObjectCode: 2638
        lineAmount: 102.15
        lineAction: D
        shipDate: 2000-01-23T04:56:07.000+00:00
        complete: false
        status: placed
      xml:
        name: Order
    Category:
      title: Pet category
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      description: A category for a pet
      example:
        name: name
        id: 6
      xml:
        name: Category
    Tag:
      title: Pet Tag
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      description: A tag for a pet
      example:
        name: name
        id: 1
      xml:
        name: Tag
    Pet:
      title: a Pet
      required:
      - name
      - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        tags:
          type: array
          xml:
            name: tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
          enum:
          - available
          - pending
          - sold
      description: A pet for sale in the pet store
      example:
        photoUrls:
        - photoUrls
        - photoUrls
        name: doggie
        id: 0
        category:
          name: name
          id: 6
        tags:
        - name: name
          id: 1
        - name: name
          id: 1
        status: available
      xml:
        name: Pet
  requestBodies:
    MO:
      description: Obligation messages are comprised of segments grouped together into associated sub-segments.  Each message begins with a Control (CTL) segment followed by a DOC (and/or BAT) segment.  The DOC Segment is comprised of sub-segments MO1-MO5.  The DOC Segment is followed by the LIN Segment (comprised of sub-segments MOA-MOC).  Messages can be "batched" into multiples using the BAT segment as a designator.  The BAT segment specifies how many DOC segments will be packaged into a given batch transmission.  Batches are limited in size however and may need to be split into multiple standalone transmissions.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MO'
        application/xml:
          schema:
            $ref: '#/components/schemas/MO'
      required: true
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: /api/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
